#THIS is development compose files
#production one wont have user/password inside yml's
version: '3.3'
volumes:
  db-volume:
services:
  database:
    image: library/mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  service:
    build:
      context: .
      dockerfile: url_shortner.Dockerfile
    links:
      - database
    ports:
      - "9090:9090"
#  proxy:
#    build:
#      context: .
#      dockerfile: envoy.Dockerfile
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
