#THIS is development compose files
#production one wont have user/password inside yml's
version: '3.3'
volumes:
  db-volume:
services:
  database:
    image: library/mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  api-service:
    build:
      context: .
      dockerfile: url_shortner.Dockerfile
    links:
      - database
    ports:
      - "9090:9090"

  redirection-service:
    build:
      context: .
      dockerfile: redirection_service.Dockerfile
    links:
      - api-service
    ports:
      - "5000:5000"

