#THIS is development compose files
#production one wont have user/password inside yml's
version: '3.3'
volumes:
  db-volume:
services:
  database:
    image: library/mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  api-service:
    image: url-shortner-api-service:${TAG:-latest}
    build:
      context: .
      dockerfile: url_shortner.Dockerfile
    links:
      - database
    expose:
      - "9090"
    ports:
      - "9090:9090"

  redirection-service:
    image: url-shortner-redirection-service:${TAG:-latest}
    build:
      context: .
      dockerfile: redirection_service.Dockerfile
    depends_on:
      - api-service
    expose:
      - "5000"
    ports:
      - "5000:5000"


  clients:
    image: url_shortner_clients:${TAG:-latest}
    build:
      context: .
      dockerfile: url_shortner_clients.Dockerfile
    depends_on:
      - redirection-service
      - api-service

